# Generated by Django 5.1.15 on 2026-02-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('LEAGUE', 'League'), ('PLAYOFF', 'Play Off'), ('LEAGUE_PLAYOFF', 'League + Play Off'), ('GROUP_PLAYOFF', 'Group + Play Off')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
