# Generated by Django 5.1.15 on 2026-02-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_user_avatar_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
