# Generated by Django 5.1.15 on 2026-02-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0004_match_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('STARTED', 'Started'), ('FINISHED', 'Finished')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='championship',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
