# Generated by Django 6.0.2 on 2026-02-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0005_championship_status_alter_championship_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='match',
            name='group',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round',
        ),
        migrations.AddField(
            model_name='championship',
            name='advance_count',
            field=models.IntegerField(default=4, help_text='Nechta jamoa pley-offga chiqadi?'),
        ),
        migrations.AddField(
            model_name='match',
            name='group_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='championship.championship'),
        ),
    ]
