# Generated by Django 6.0.2 on 2026-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0006_remove_championship_created_by_remove_match_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='draw_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='championship',
            name='loss_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='championship',
            name='matches_per_team',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='championship',
            name='teams_count',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='championship',
            name='win_points',
            field=models.IntegerField(default=3),
        ),
    ]
