# Generated by Django 6.0.2 on 2026-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0007_championship_draw_points_championship_loss_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='advance_count',
            field=models.IntegerField(default=4),
        ),
    ]
