# Generated by Django 6.0.2 on 2026-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0008_alter_championship_advance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
