# Generated by Django 6.0.2 on 2026-02-23 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0009_match_bracket_position_match_next_match_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
