# Generated by Django 6.0.2 on 2026-02-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0010_match_next_match_id_match_round_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
