# Generated by Django 6.0.2 on 2026-02-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0011_championship_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
