# Generated by Django 6.0.2 on 2026-02-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='next_match_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
