# Generated by Django 6.0.2 on 2026-02-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0013_alter_match_next_match_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='next_match_id',
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='championship.match'),
        ),
    ]
