# Generated by Django 6.0.2 on 2026-02-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0014_remove_match_next_match_id_match_next_match'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['championship', 'is_finished'], name='championshi_champio_0ecad9_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['championship', 'round_order'], name='championshi_champio_f2c69c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_user'], name='championshi_home_us_8a0f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_user'], name='championshi_away_us_fdf260_idx'),
        ),
    ]
