# Generated by Django 6.0.2 on 2026-02-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0015_match_championshi_champio_0ecad9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='type',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('PLAYOFF', 'Play Off'), ('GROUP', 'Group')], max_length=20),
        ),
    ]
