# Generated by Django 6.0.2 on 2026-02-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0016_alter_championship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='group_advance_count',
            field=models.IntegerField(default=1, verbose_name='Har bir guruhdan chiqadigan jamoalar soni'),
        ),
        migrations.AddField(
            model_name='championship',
            name='group_count',
            field=models.IntegerField(default=4, verbose_name='Guruhlar soni'),
        ),
    ]
