# Generated by Django 6.0.2 on 2026-03-04 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0018_bookmarkedmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0, verbose_name="O'yinlar soni")),
                ('points', models.IntegerField(default=0, verbose_name='Ochkolar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', '-games_played'],
            },
        ),
    ]
