# Generated by Django 6.0.2 on 2026-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0019_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nation',
            field=models.CharField(blank=True, choices=[('UZ', '🇺🇿 O`zbekiston'), ('KG', '🇰🇬 Qirg`iziston'), ('KZ', '🇰🇿 Qozog`iston'), ('TJ', '🇹🇯 Tojikiston'), ('AM', '🇦🇲 Armenia'), ('AZ', '🇦🇿 Ozarbayjon'), ('BY', '🇧🇾 Belarusiya'), ('RU', '🇷🇺 Rossiya'), ('OTHER', '🌍 Boshqa')], default='UZ', max_length=10, null=True, verbose_name='Davlat'),
        ),
    ]
