# Generated by Django 6.0.2 on 2026-03-06 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0020_user_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150, verbose_name='Turnir nomi')),
                ('tournament_image', models.ImageField(blank=True, null=True, upload_to='tournament_images/', verbose_name='Turnir rasmi')),
                ('position', models.IntegerField(choices=[(1, "🥇 1-o'rin"), (2, "🥈 2-o'rin"), (3, "🥉 3-o'rin")], verbose_name="O'rin")),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('is_automatic', models.BooleanField(default=False, verbose_name="Avtomatik qo'shilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_championship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champions_generated', to='championship.championship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championships_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'position'],
                'unique_together': {('user', 'tournament_name', 'year', 'position')},
            },
        ),
    ]
