# Generated by Django 6.0.2 on 2026-03-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0021_champion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['-year', '-created_at'], 'verbose_name': 'Chempion', 'verbose_name_plural': 'Chempionlar'},
        ),
        migrations.AlterUniqueTogether(
            name='champion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='champion',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champions', to='championship.championship'),
        ),
        migrations.AddField(
            model_name='champion',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='champion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='position',
            field=models.IntegerField(choices=[(1, "🥇 1-o'rin"), (2, "🥈 2-o'rin"), (3, "🥉 3-o'rin")]),
        ),
        migrations.AlterField(
            model_name='champion',
            name='tournament_image',
            field=models.ImageField(blank=True, null=True, upload_to='champions/tournaments/'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='champion',
            name='is_automatic',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='source_championship',
        ),
    ]
