# Generated by Django 5.1.3 on 2026-03-07 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0022_alter_champion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarkedmatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarklar'},
        ),
        migrations.AlterModelOptions(
            name='championship',
            options={'verbose_name': 'Turnir', 'verbose_name_plural': 'Turnirlar'},
        ),
        migrations.AlterModelOptions(
            name='championshipparticipant',
            options={'verbose_name': 'Turnir ishtirokchisi', 'verbose_name_plural': 'Turnir ishtirokchilari'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': "O'yin", 'verbose_name_plural': "O'yinlar"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'ordering': ['-points', '-games_played'], 'verbose_name': 'User reytingi', 'verbose_name_plural': 'User reytinglari'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TOURNAMENT', 'Turnir ishtirokchisi'), ('RATING', 'Reyting ishtirokchisi'), ('CHAMPION', 'Chempion'), ('ALL', 'Hamma sectionlarda')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='championship',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
        migrations.CreateModel(
            name='ChampionHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, "🥇 1-o'rin"), (2, "🥈 2-o'rin"), (3, "🥉 3-o'rin")], verbose_name="O'rin")),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('tournament_name', models.CharField(max_length=200, verbose_name='Turnir nomi')),
                ('tournament_image', models.ImageField(blank=True, null=True, upload_to='champion_halls/', verbose_name='Turnir rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_halls', to=settings.AUTH_USER_MODEL, verbose_name='Chempion')),
            ],
            options={
                'verbose_name': 'Champion Hall',
                'verbose_name_plural': 'Champion Hall',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_tournament', models.BooleanField(default=True, verbose_name="Turnirlarda ko'rinadi")),
                ('in_rating', models.BooleanField(default=True, verbose_name="Reytingda ko'rinadi")),
                ('in_champions', models.BooleanField(default=True, verbose_name="Chempionlar ro'yxatida ko'rinadi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User turi',
                'verbose_name_plural': 'User turlari',
            },
        ),
        migrations.DeleteModel(
            name='Champion',
        ),
    ]
