# Generated by Django 5.1.3 on 2026-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0024_alter_championhall_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championhall',
            options={'ordering': ['-year', '-tournament_date', '-created_at'], 'verbose_name': 'Champion Hall', 'verbose_name_plural': 'Champion Hall'},
        ),
        migrations.AddField(
            model_name='championhall',
            name='tournament_date',
            field=models.DateField(blank=True, null=True, verbose_name='Turnir sanasi'),
        ),
    ]
