# Generated by Django 5.1.3 on 2026-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0025_alter_championhall_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championhall',
            options={'ordering': ['-tournament_date', '-created_at'], 'verbose_name': 'Champion Hall', 'verbose_name_plural': 'Champion Hall'},
        ),
        migrations.RemoveField(
            model_name='championhall',
            name='year',
        ),
        migrations.AlterField(
            model_name='championhall',
            name='tournament_date',
            field=models.DateField(default='2024-01-01', verbose_name='Turnir sanasi'),
            preserve_default=False,
        ),
    ]
