# Generated by Django 5.1.3 on 2026-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0026_alter_championhall_options_remove_championhall_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championhall',
            name='position',
            field=models.IntegerField(choices=[(1, '1-o`rin'), (2, '2-o`rin'), (3, '3-o`rin')], verbose_name="O'rin"),
        ),
    ]
