from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('championships/', views.championship_list, name='championship_list'),
    path('championships/create/', views.create_championship, name='create_championship'),
    path('championships/<int:pk>/generate/', views.generate_matches, name='generate_matches'),
    path('championships/<int:pk>/add-user/', views.add_participant, name='add_participant'),
    path('championships/<int:pk>/participants/', views.create_participant, name='create_participant'),
    path('championships/<int:pk>/matches/', views.championship_matches, name='championship_matches'),
    path('championships/<int:pk>/table/', views.championship_table, name='championship_table'),
    path('championship/<int:pk>/update-all-scores/', views.update_all_scores, name='update_all_scores'),
    path('profile/', views.update_profile, name='update_profile'),

    path('users/', views.admin_users, name='admin_users'),
    path('users/<int:pk>/', views.admin_user_detail, name='admin_user_detail'),

    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/championship/<int:pk>/settings/', views.admin_championship_detail, name='admin_championship_detail'),
    path('admin/championship/<int:pk>/bulk-add/', views.bulk_add_participants, name='bulk_add_participants'),
    path('admin/championship/<int:pk>/generate/', views.generate_matches, name='generate_matches'),
    path('get-championship-data/<int:pk>/', views.get_championship_data, name='get_championship_data'),
    path('admin/championship/<int:pk>/delete/', views.delete_championship, name='delete_championship'),
    path('admin/championship/<int:pk>/remove-participant/<int:user_id>/', views.remove_participant, name='remove_participant'),
    path('admin/users/delete/<int:pk>/', views.admin_delete_user, name='admin_delete_user'),
    path('match/<int:match_id>/update-single/', views.update_single_match, name='update_single_match'),
    path('toggle-bookmark/<int:match_id>/', views.toggle_bookmark, name='toggle_bookmark'),
    path('get-bookmarks/', views.get_user_bookmarks, name='get_user_bookmarks'),
    path('tournament/<int:pk>/', views.tournament_public_view, name='tournament_public_view'),
    path('tournament-detail/<int:pk>/partial/', views.tournament_detail_partial, name='tournament_detail_partial'),
    path('update-ratings/', views.update_ratings, name='update_ratings'),
    path('admin/championship/<int:pk>/finish/', views.finish_championship, name='finish_championship'),
    
    # CHAMPIONS HALL URLS - FAQAT SHULAR
    path('champions/', views.champions_page, name='champions_page'),
    path('champions/data/', views.champions_page_data, name='champions_data'),
    path('admin/champions/add/', views.add_champion_hall, name='add_champion_hall'),
    path('admin/champions/<int:pk>/edit/', views.edit_champion_hall, name='champion_hall_edit'),
    path('admin/champions/<int:pk>/delete/', views.champion_hall_delete, name='champion_hall_delete'),
    path('admin/users/<int:user_id>/champions/', views.user_champions, name='user_champions'),
    path('admin/users/<int:user_id>/champions/add/', views.add_champion_to_user, name='add_champion_to_user'),
    path('champions/<int:pk>/data/', views.champion_detail_data, name='champion_detail_data'),
    path('admin/ratings/delete/<int:user_id>/', views.delete_rating, name='delete_rating'),
    path('admin/ratings/delete/<int:user_id>/ajax/', views.delete_rating_ajax, name='delete_rating_ajax'),
    path('api/user-champions/<int:user_id>/', views.user_champions_api, name='user_champions_api'),
    path('champions/<int:pk>/data/', views.champion_detail_data, name='champion_detail_data'),
]